micronaut:
  application:
    name: petClinicReviews
  server:
    port: 32583


mongodb:
  uri: mongodb://mongodb:mongodb@host.docker.internal:27017/pet-clinic-reviews
  databaseName: pet-clinic-reviews
  collectionName: vet-reviews


kafka:
  bootstrap:
    servers: localhost:9094

endpoints:
  all:
    enabled: true
    sensitive: false

consul:
  client:
    default-zone: "consul:8500"
    registration:
      enabled: true