micronaut:
  application:
    name: petOwner
  router:
    versioning:
      enabled: true
      default-version: 1
      parameter:
        enabled: false
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root

jpa:
  default:
    entity_scan:
      packages:
        - com.pet.domain
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        enable_lazy_load_no_trans: true
