micronaut:
  application:
    name: petClinicConcierge
  config-client:
    enabled: true
  server:
    port: 32584


consul:
  client:
    registration:
      enabled: true
    default-zone: "consul:8500"
