micronaut:
  application:
    name: petClinicConcierge
  config-client:
    enabled: true
  server:
    port: 32584


consul:
  client:
    registration:
      enabled: true
    default-zone: "consul:8500"

tracing:
  zipkin:
    http:
      url: http://host.docker.internal:9411
    enabled: true
    sampler:
      probability: 1